version: "3.7"

services:
    tu-gerente-challenge:
        container_name: react
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./tu-gerente-challenge:/app"
        ports:
            - 3000:3000
        environment:
            - WATCHPACK_POLLING=true
